apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: operatorhub-and-catalogs
  namespace: {{ .Values.clusterNamespace }}
spec:
  clusterDeploymentRefs:
    - name: {{ .Values.clusterDeploymentName }}
  resourceApplyMode: Sync
  resources:
    # Disable all default sources in OperatorHub
    - apiVersion: config.openshift.io/v1
      kind: OperatorHub
      metadata:
        name: cluster
      spec:
        disableAllDefaultSources: true

{{- range .Values.catalogs }}
    # ClusterCatalog: {{ .name }}
    - apiVersion: olm.operatorframework.io/v1
      kind: ClusterCatalog
      metadata:
        name: {{ .name }}
      spec:
        priority: 0
        source:
          image:
            ref: {{ .image }}
{{- end }}

