apiVersion: hive.openshift.io/v1
kind: SyncSet
metadata:
  name: imagedigestmirrorsets
  namespace: {{ .Values.clusterNamespace }}
spec:
  clusterDeploymentRefs:
    - name: {{ .Values.clusterDeploymentName }}
  resourceApplyMode: Sync
  resources:
{{- range .Values.imageDigestMirrorSets }}
    - apiVersion: config.openshift.io/v1
      kind: ImageDigestMirrorSet
      metadata:
        name: {{ .name }}
      spec:
        imageDigestMirrors:
{{- range .mirrors }}
          - source: {{ .source }}
            mirrors:
{{- range .mirrors }}
              - {{ . }}
{{- end }}
{{- end }}
{{- end }}

